export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const SET_GAME_FIELD = 'SET_GAME_FIELD';
export const SET_GAME_FIELD_SIZE = 'SET_GAME_FIELD_SIZE';
export const UPDATE_GAME_FIELD_TILE = 'UPDATE_GAME_FIELD_TILE';
export const SET_GAME_MODE = 'SET_GAME_MODE';
export const SET_NEED_TO_BE_GUESSED = 'SET_NEED_TO_BE_GUESSED';